### ISSUE TITLE
Apresentação Sprint l

### ISSUE THREAD

**Issue by taiinteli** [Inteli-College/2024-T0002-EC09-G05#13]
**Slides:** 

- [x] Roteiro; 
- [x] Design; 
- [x] Validação com o grupo/prof; 
- [x] Ensaiar;

**Comment by cmtabr** [comment]
O professor só comentou do roteiro, na hora de fazer as trocas entre apresentadores. 
Tirando esse ponto de atenção para a próxima sprint, ficou muito bom
