### ISSUE TITLE
Perguntas ao Parceiro

### ISSUE THREAD

**Issue by taiinteli** [Inteli-College/2024-T0002-EC09-G05#14]
**TAPI:** https://docs.google.com/document/d/15Z7xMHzdsVBHOvIR-BQjqVmZohKrPUJz/edit

**Perguntas:** https://docs.google.com/document/d/1c1EmJPF3Q_CRDbdCHiYrc1rjurAlsCKbbMHVLmJfbcY/edit?usp=sharing

**Comment by cmtabr** [comment]
O kick off foi realizado com o parceiro no dia 07/02 e as perguntas realizadas estão endereçadas no arquivo [Docs](https://docs.google.com/document/d/1c1EmJPF3Q_CRDbdCHiYrc1rjurAlsCKbbMHVLmJfbcY/edit), que também pode ser encontrado na pasta "Projeto" nos marcadores no canal do Slack do grupo
