### ISSUE TITLE
[Negócios] [Peso 1] Matriz de Risco

### ISSUE THREAD

**Issue by cmtabr** [Inteli-College/2024-T0002-EC09-G05#4]
**Tarefas:**
- [ ] Ter minimamente 10 riscos contingentes ou não discutidos em grupo
- [x] Seguir o template contido no [Drive](https://drive.google.com/drive/u/3/folders/1lTqisJ_gxxtc5J5aXM8ula2kQ4MsII_M) 
- [x] Deve levar em consideração o projeto (Extremamente necessário ter **validação** do **Grupo)**

**Considerações:**

**Padrão de Qualidade:**
- [x] Justificativa para mitigação de risco para cada elemento elencado

**Comment by cmtabr** [comment]
Parte da matriz foi desenvolvida levando em consideração os requisitos necessários para avaliação do professor orientador, cabendo contribuição dos demais membros encarregados da tarefa. 

**Links:**

**Comment by paulo-evangelista** [comment]
Como o membro responsável @ViniciosLugli não cumpriu sua parte, eu mesmo adicionei os 5 riscos restantes.
