### ISSUE TITLE
[Negócios] [Peso 2] Plano de Comunicação

### ISSUE THREAD

**Issue by cmtabr** [Inteli-College/2024-T0002-EC09-G05#5]
**Tarefas:**
Definição do Propósito: Antes de começar, determine o propósito ou objetivo principal da comunicação. O que você espera alcançar? (Por exemplo: Informar os funcionários sobre uma mudança organizacional, promover um novo produto, etc.)
- [x] Público-alvo: Quem é o principal público da sua comunicação? O que eles já sabem sobre o tópico? Qual é o nível de interesse e atitude deles em relação ao tópico?
- [x] Mensagens-chave: Quais são os principais pontos ou informações que você deseja transmitir? Certifique-se de que sejam claros, concisos e relevantes para o público-alvo.
- [x] Canais de Comunicação: Que meios você usará para comunicar? (Por exemplo: e-mail, mídias sociais, reuniões presenciais, etc.)
- [x]  Cronograma: Defina um cronograma para quando e como a comunicação será disseminada. Considere a frequência e a fase do projeto.

**Considerações:**

**Padrão de Qualidade:**
- [x] Clareza e Relevância: As mensagens-chave são claras e pertinentes ao público-alvo?
- [x] Adequação do Canal: Os canais de comunicação escolhidos são apropriados para o público e a mensagem?
- [x] Eficiência do Cronograma: O cronograma é realista e alinhado com os objetivos de comunicação?

**Comment by cmtabr** [comment]
**Referências utilizadas:**
1. [Plano de Comunicação em 7 passos](https://www.cortex-intelligence.com/blog/comunicacao/plano-de-comunicacao-eficaz)
2. [Metodologia SMART](https://deolhonofuturo.uninter.com/metodologia-smart/)

**Comment by MihaellK** [comment]
citar secretarias do estado na seção de publico externo -> 'O público externo é composto por todas as partes interessadas que não fazem parte da equipe de desenvolvimento do projeto, incluindo os clientes, usuários finais, secretarias estaduais, como do Meio Ambiente, da Saude, da Educação e outras partes interessadas'

Ponto 3 da seção de **Objetivos**, corrigir repetição de palavra -> Alcançável: A comunicação será feita **através** **de** através de reuniões presenciais

**Comment by cmtabr** [comment]
**Commit de resolução:**
https://github.com/Inteli-College/2024-T0002-EC09-G05/commit/302819804485105e48067c98c5265eea36e5e957

Foi corrigida a escrita na seção objetivos relativos ao público externo, adicionados exemplos de usuários finais e incluídas informações adicionais referentes ao meio de divulgação

**Comment by cmtabr** [comment]
**Commit de resolução:**
https://github.com/Inteli-College/2024-T0002-EC09-G05/commit/302819804485105e48067c98c5265eea36e5e957

Foi corrigida a escrita na seção objetivos relativos ao público externo, adicionados exemplos de usuários finais e incluídas informações adicionais referentes ao meio de divulgação 

> citar secretarias do estado na seção de publico externo -> 'O público externo é composto por todas as partes interessadas que não fazem parte da equipe de desenvolvimento do projeto, incluindo os clientes, usuários finais, secretarias estaduais, como do Meio Ambiente, da Saude, da Educação e outras partes interessadas'
> 
> Ponto 3 da seção de **Objetivos**, corrigir repetição de palavra -> Alcançável: A comunicação será feita **através** **de** através de reuniões presenciais
