### ISSUE TITLE
[Negócios] [Peso 2] Análise Financeira

### ISSUE THREAD

**Issue by cmtabr** [Inteli-College/2024-T0002-EC09-G05#6]
**Tarefas:**
- [x] Deve ser informado o quanto o parceiro tem projetado para investir no projeto e quais são as projeções de custos e de receitas que o parceiro projeta ter relacionadas ao projeto (para o período de um ano). Ressalta-se que é uma estimativa.

**Considerações:**
Caso o projeto seja interno, não existindo vendas (receita), não é necessário informar a receita estimada. Para que a entrega seja realizada, basta informar esses dados e a lógica que o parceiro forneceu para alcançá-los. 

**Padrão de Qualidade:**
- [x] Informar o quanto o parceiro tem projetado para investir no projeto e quais são as projeções de custos e de receitas que o parceiro projeta ter relacionadas ao projeto (para o período de um ano). 
> [!Note] 
> Ressalta-se que é uma estimativa.

**Comment by cmtabr** [comment]
É importante adicionar os custos dos sensores na análise e informar que não foi passado uma estimativa de investimento para o projeto, pois se trata de uma ferramenta de uso do setor público.

**Comment by Kil-Matheus** [comment]
Ok, será acrescentado no Documento com requirido. Agradeço o retorno

**Comment by cmtabr** [comment]
Validação realizada
