### ISSUE TITLE
[Programação] Simulador MQTT

### ISSUE THREAD

**Issue by JvLetsBora** [Inteli-College/2024-T0002-EC09-G05#7]
**Parâmetros:**
- [x] Estrutura do Código-Fonte e Organização no GitHub; 
- [x] Testes Automatizados e Manuais; 
- [x] Instruções de Execução para Parceiros;
- [x] Release do Projeto com Numeração de Sprint.

**Tarefas:**
- [x] Implementar um cliente MQTT que se comunica com um broker público.
- [x] Criar testes unitários para o cliente MQTT desenvolvido

**Considerações:**
- As questões centrais de desenvolvimento da sprint e os testes devem ser apresentadas de forma clara durante o review com o parceiro.

**Padrão de Qualidade:**
- [x] Disponibilizar o código fonte da solução em um diretório denominado src.
- [x] Disponibilizar os testes no diretório tests e, quando possível, aplicados de forma automatizada. Os testes realizados sem automatização devem ter seu procedimento de execução e resultados claramente descritos em um arquivo contido dentro do diretório de testes. testes e os resultados em um arquivo markdown dentro da pasta 'tests'.
- [x] As instruções para que o parceiro possa executar o projeto devem estar claramente discriminadas na documentação, com um link no README para que a seção possa ser prontamente acessada.
- [x] O projeto em seu estado atual deve estar disponível em um release do Github cujo nome deve incluir a numeração da sprint.

**Comment by MihaellK** [comment]
Testes manuais adicionados e junto com instrução que se encontra no README da pasta 'tests'
[18d50384073c471880060732f8ade8a0f5bae373](https://github.com/Inteli-College/2024-T0002-EC09-G05/commit/18d50384073c471880060732f8ade8a0f5bae373)
