### ISSUE TITLE
[Design] Persona

### ISSUE THREAD

**Issue by taiinteli** [Inteli-College/2024-T0002-EC09-G05#8]
**Tarefas:** 

- [x] Usar o Template; 
           - Foto ou ilustração representativa; 
           - Nome Fictício;
           - Informações Demográficas;
           - Background; 
           - Dores, Necessidades e Desejos; 
           - Cenários de Interação; 
           - Interesses e Hábitos; 
           - Nível de Letramento Digital; 
           - Citações Diretas; 
           - Contexto Urbano; 

- [x] Completude da Persona; 

- [x] Profundidade e Realismo; 

- [x] Design e Apresentação; 

- [x] Relevância e Contexto Urbano.

**Comment by cmtabr** [comment]
O critério do contexto urbano é muito importante aqui, acredito que não tenha ficado muito claro nas personas. Faltou a explicação dele no card, mas a avaliação vai se basear nos pontos abaixo: 
- [ ] Descrição do ambiente da cidade onde a persona vive, detalhando características como acessibilidade, conectividade, infraestrutura disponível, principais desafios urbanos e oportunidades na região.

Acho que é o que falta, sobre o quesito "citações diretas", não vejo muita necessidade de incluir, pouco relevante na correção.

Tirando isso mandou bem, ficou bem bonito a propósito.

**Comment by Kil-Matheus** [comment]
Pode deixar que eu atualizo as personas sim. Agradeço o retorno

**Comment by Kil-Matheus** [comment]
Personas estão corrigidas com o Card pede, fico a disposição para eventuais
dúvidas
